Command: /home/minipops/.espressif/python_env/idf5.5_py3.13_env/bin/python /opt/esp-idf/tools/idf_monitor.py -p /dev/ttyUSB0 -b 115200 --toolchain-prefix xtensa-esp32-elf- --target esp32 --revision 0 /home/minipops/uni/da267a/labs/lab5/build/lab5.elf /home/minipops/uni/da267a/labs/lab5/build/bootloader/bootloader.elf -m '/home/minipops/.espressif/python_env/idf5.5_py3.13_env/bin/python' '/opt/esp-idf/tools/idf.py'
[0;33m--- esp-idf-monitor 1.7.0 on /dev/ttyUSB0 115200[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H[0m
[0m--- 0x40080400: [0;33m_invalid_pc_placeholder[0m[0m at [0;32m/opt/esp-idf/components/xtensa/xtensa_vectors.S[0m[0m:[1;31m2235[0m
[0m--- 0x40080638: [0;33mcall_start_cpu0[0m[0m at [0;32m/opt/esp-idf/components/bootloader/subproject/main/bootloader_start.c[0m[0m:[1;31m25[0m
[1;31m--- Error: device reports readiness to read but returned no data (device disconnected or multiple access on port?)[0m
[0;33m--- Waiting for the device to reconnect[0m[0;33m[0m
[0m--- 0x40080400: [0;33m_invalid_pc_placeholder[0m[0m at [0;32m/opt/esp-idf/components/xtensa/xtensa_vectors.S[0m[0m:[1;31m2235[0m
[0m--- 0x40080638: [0;33mcall_start_cpu0[0m[0m at [0;32m/opt/esp-idf/components/bootloader/subproject/main/bootloader_start.c[0m[0m:[1;31m25[0m
[0m--- 0x40084090: [0;33m_xt_panic[0m[0m at [0;32m/opt/esp-idf/components/esp_system/port/arch/xtensa/panic_handler_asm.S[0m[0m:[1;31m30[0m
[0m--- 0x4008473e: [0;33mesp_cpu_wait_for_intr[0m[0m at [0;32m/opt/esp-idf/components/esp_hw_support/cpu.c[0m[0m:[1;31m64[0m
[1;31m--- Error: device reports readiness to read but returned no data (device disconnected or multiple access on port?)[0m
[0;33m--- Waiting for the device to reconnect[0m[0;33m[0m
[0m
